// <auto-generated />
using System;
using GMO.Family.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GMO.Family.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222200000_AddUserProfile")]
    partial class AddUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is in AppDbContextModelSnapshot
        }
    }
}
