// <auto-generated />
using GMO.FamilyTree.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GMO.FamilyTree.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222230000_MakeOwnerIdRequiredAndAddFk")]
    partial class MakeOwnerIdRequiredAndAddFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is in AppDbContextModelSnapshot
        }
    }
}
